import numpy as np

def get_env_kwargs(agent_args):
    OD2 = [[0., 0.9],
        [0.2, 0.]]
    C2 = [[0., 5.],
        [2., 0.]]
    init_passenger_distribution2 = [2000., 3000.]
    init_driver_distribution2 = [500., 1000.]

    # Set vector_state to false in order to use visual observations (significantly longer training time)
    ts = 8*864000
    d = 0.05
    env_kwargs = {
        "OD":                                       np.array(OD2),
        "C":                                        np.array(C2),
        "init_passenger_distribution":              np.array(init_passenger_distribution2),
        "init_driver_distribution":                 np.array(init_driver_distribution2),
        "max_rate":         20.,                    # maximum charged per mile is 20
        "max_timestep":     ts ,                    # seconds in a day [Deprecated]
        "lbd":              2.,                     # Base waiting cost lambda
        "rp":               10.,                    # public transportation charges
        "g":                5.,                     # gas cost
        "num_D_samples":    10,                     # random samples generated by drivers
        "a_d":              d,                      # at each second, can only change by this much
        "p_d":              1.,                     # Passengers responsive
        "alpha":            1e-2,                   # step parameter for continuous term
        "mode":             "interp",               # Always interp. "delta" deprecated
        "traj_length":      agent_args["traj_length"]
    }

    return env_kwargs
